services:
  postgresdb:
    image: pgvector/pgvector:pg16
    container_name: developer-website-db
    restart: always
    env_file:
      - docker.env
    ports:
      - '${POSTGRES_PORT_EXTERNAL:-5432}:5432'
    volumes:
      - postgres_dev_website_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  website:
    container_name: developer-website-app
    build:
      context: .
      target: builder
    env_file:
      - docker.env
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgresdb:
        condition: service_healthy
    command: yarn dev --host 0.0.0.0
    environment:
      # hot reload enabled
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_dev_website_data_dev:
