services:
  postgresdb:
    env_file:
      - docker-prod.env
    volumes:
      - postgres_website_data_prod:/var/lib/postgresql/data

  website:
    build:
      target: runner
    env_file:
      - docker-prod.env
    environment:
      NODE_ENV: production

volumes:
  postgres_website_data_prod:
