server {
    listen 80;
    
    # Serve static files for /cdn/
    # Serve static files for /cdn/projects/
    location /cdn/projects/ {
        alias /usr/share/nginx/html/shared/projects/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Serve static files for /cdn/me/
    location /cdn/me/ {
        alias /usr/share/nginx/html/shared/me/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Serve static files for /cdn/ (fallback for old URLs)
    location /cdn/ {
        alias /usr/share/nginx/html/shared/projects/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Serve static files for /cdn/temp/
    location /cdn/temp/ {
        alias /usr/share/nginx/html/shared/temp/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Proxy all other requests to the Node.js application
    location / {
        proxy_pass http://website:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
