/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as ApiOptimizeImageRouteImport } from './routes/api.optimize-image'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminSettingsThemesRouteImport } from './routes/admin.settings.themes'
import { Route as AdminSettingsPrivacyRouteImport } from './routes/admin.settings.privacy'
import { Route as AdminSettingsLegalMentionsRouteImport } from './routes/admin.settings.legal-mentions'
import { Route as AdminSettingsCookiePolicyRouteImport } from './routes/admin.settings.cookie-policy'
import { Route as AdminSettingsCguRouteImport } from './routes/admin.settings.cgu'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOptimizeImageRoute = ApiOptimizeImageRouteImport.update({
  id: '/api/optimize-image',
  path: '/api/optimize-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsThemesRoute = AdminSettingsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPrivacyRoute = AdminSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsLegalMentionsRoute =
  AdminSettingsLegalMentionsRouteImport.update({
    id: '/legal-mentions',
    path: '/legal-mentions',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsCookiePolicyRoute =
  AdminSettingsCookiePolicyRouteImport.update({
    id: '/cookie-policy',
    path: '/cookie-policy',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsCguRoute = AdminSettingsCguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => AdminSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/api/optimize-image': typeof ApiOptimizeImageRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/settings/cgu': typeof AdminSettingsCguRoute
  '/admin/settings/cookie-policy': typeof AdminSettingsCookiePolicyRoute
  '/admin/settings/legal-mentions': typeof AdminSettingsLegalMentionsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/admin/settings/themes': typeof AdminSettingsThemesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/api/optimize-image': typeof ApiOptimizeImageRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/settings/cgu': typeof AdminSettingsCguRoute
  '/admin/settings/cookie-policy': typeof AdminSettingsCookiePolicyRoute
  '/admin/settings/legal-mentions': typeof AdminSettingsLegalMentionsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/admin/settings/themes': typeof AdminSettingsThemesRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/api/optimize-image': typeof ApiOptimizeImageRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/admin/settings/cgu': typeof AdminSettingsCguRoute
  '/admin/settings/cookie-policy': typeof AdminSettingsCookiePolicyRoute
  '/admin/settings/legal-mentions': typeof AdminSettingsLegalMentionsRoute
  '/admin/settings/privacy': typeof AdminSettingsPrivacyRoute
  '/admin/settings/themes': typeof AdminSettingsThemesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/projects'
    | '/services'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/profiles'
    | '/admin/projects'
    | '/admin/settings'
    | '/api/optimize-image'
    | '/projects/$slug'
    | '/admin/settings/cgu'
    | '/admin/settings/cookie-policy'
    | '/admin/settings/legal-mentions'
    | '/admin/settings/privacy'
    | '/admin/settings/themes'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/projects'
    | '/services'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/profiles'
    | '/admin/projects'
    | '/api/optimize-image'
    | '/projects/$slug'
    | '/admin/settings/cgu'
    | '/admin/settings/cookie-policy'
    | '/admin/settings/legal-mentions'
    | '/admin/settings/privacy'
    | '/admin/settings/themes'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/projects'
    | '/services'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/profiles'
    | '/admin/projects'
    | '/admin/settings'
    | '/api/optimize-image'
    | '/projects_/$slug'
    | '/admin/settings/cgu'
    | '/admin/settings/cookie-policy'
    | '/admin/settings/legal-mentions'
    | '/admin/settings/privacy'
    | '/admin/settings/themes'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  ApiOptimizeImageRoute: typeof ApiOptimizeImageRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/optimize-image': {
      id: '/api/optimize-image'
      path: '/api/optimize-image'
      fullPath: '/api/optimize-image'
      preLoaderRoute: typeof ApiOptimizeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/themes': {
      id: '/admin/settings/themes'
      path: '/themes'
      fullPath: '/admin/settings/themes'
      preLoaderRoute: typeof AdminSettingsThemesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/privacy': {
      id: '/admin/settings/privacy'
      path: '/privacy'
      fullPath: '/admin/settings/privacy'
      preLoaderRoute: typeof AdminSettingsPrivacyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/legal-mentions': {
      id: '/admin/settings/legal-mentions'
      path: '/legal-mentions'
      fullPath: '/admin/settings/legal-mentions'
      preLoaderRoute: typeof AdminSettingsLegalMentionsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/cookie-policy': {
      id: '/admin/settings/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/admin/settings/cookie-policy'
      preLoaderRoute: typeof AdminSettingsCookiePolicyRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/cgu': {
      id: '/admin/settings/cgu'
      path: '/cgu'
      fullPath: '/admin/settings/cgu'
      preLoaderRoute: typeof AdminSettingsCguRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsCguRoute: typeof AdminSettingsCguRoute
  AdminSettingsCookiePolicyRoute: typeof AdminSettingsCookiePolicyRoute
  AdminSettingsLegalMentionsRoute: typeof AdminSettingsLegalMentionsRoute
  AdminSettingsPrivacyRoute: typeof AdminSettingsPrivacyRoute
  AdminSettingsThemesRoute: typeof AdminSettingsThemesRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsCguRoute: AdminSettingsCguRoute,
  AdminSettingsCookiePolicyRoute: AdminSettingsCookiePolicyRoute,
  AdminSettingsLegalMentionsRoute: AdminSettingsLegalMentionsRoute,
  AdminSettingsPrivacyRoute: AdminSettingsPrivacyRoute,
  AdminSettingsThemesRoute: AdminSettingsThemesRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  ApiOptimizeImageRoute: ApiOptimizeImageRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
